use_frameworks!

platform :ios, '10.0'

target 'NHT_Category_Example' do
  pod 'NHT_Category', :path => '../'

  target 'NHT_Category_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
